version: '3.8'

services:  
  db:
    container_name: db
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always    
    image: gandigap/rsdb:latest
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}    
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    networks:
      - home-library-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/log/postgresql
      
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    image: gandigap/rsapp:latest
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    networks:
      - home-library-network
    volumes:
      - ./src:/app/src
    environment:
      - TYPEORM_HOST=db

networks:
  home-library-network:
    driver: bridge

volumes:
  pgdata:
  pglogs: